# Setup
title: LekoDeveloperWeb
tagline: Alex Leko
description: Desenvolvimento web, mobile, aventuras no mundo corporativo e muito aprendizado.
url: https://lekodeveloperweb.github.io
baseurl: /
read_time: true

social:
    name: Alex Leko
    links:
        - https://twitter.com/LekoDeveloper
        - https://www.facebook.com/lekooficial
        - https://www.linkedin.com/in/lekodeveloperweb
        - https://github.com/lekowebdeveloper
lang: pt_BR

authors:
    alexleko:
        name: Alex Leko
        bio: Desenvolvedor Web, Apaixonado por tecnologia. Trabalhando com as linguagens C#, NodeJS, Python, GoLang e frameworks Angular, VueJS e Reactjs.
        external-image: false
        picture: public/images/profile.jpg
        twitter: LekoDeveloper

paginate: 5
paginate_path: '/blog/page:num/'

# post description
share_description: Um blog com o melhor do desenvolvimento web, mobile, e muito aprendizado.

# if it's an external image, update below for true
# better with square images
external-image: false
company_logo: public/images/favicon/icon.png
picture: public/images/profile.jpg

# If you want to include your resume, set to true
# and specify source (external or local).
resume_url: https://www.linkedin.com/in/lekodeveloperweb/

url: https://lekodeveloperweb.github.io

permalink: /blog/:title/

# To enable google analytics, supply your token below
analytics_google: 'UA-135069212-1'

# not build future post
future: false

# if you don't want comments in your posts, leave categories empty
disqus:
    shortname: LDWSolucoesInteligentes # enter this from your disqus account
    categories: [blog, project] # only show disqus for posts that have these categories

# if you don't have any of social below, comment the line
twitter: LekoDeveloper
facebook: lekooficial
instagram: alexleko
linkedin: lekodeveloperweb
spotify: lekodeveloperweb
github: lekodeveloperweb
gitlab: lekodeveloperweb
reddit: lekodeveloperweb
medium: lekodeveloperweb
email: lekodeveloperweb@hotmail.com

twitter:
    username: LekoDeveloper
    card: Desenvolvedor Web, Apaixonado por tecnologia. Trabalhando com as linguagens C#, NodeJS, Python, GoLang e frameworks Angular, VueJS e Reactjs.


# Custom vars
version: 2.0.0

github:
  repo: https://github.com/lekodeveloperweb

# Build settings
plugins:
    - jekyll-seo-tag
    - jekyll-gist
    - jekyll-feed
    - jemoji
    - jekyll-admin
    - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
