# Setup
title: LDW
tagline: 'Alex Leko'
description: 'O melhor do desenvolvimento web, mobile e gerenciamento de mídias sociais. <a href="mailto:lekodeveloperweb@hotmail.com" target="_blank">@alexleko</a>'
url: http://ldwsolucoesinteligentes.com.br
baseurl: /
read_time: true

social:
    name: Alex Leko
    links:
        - https://twitter.com/LekoDeveloper
        - https://www.facebook.com/ldwsolucoesinteligentes
        - https://www.linkedin.com/in/lekodeveloperweb
        - https://github.com/lekowebdeveloper
lang: pt_BR

authors:
    alexleko:
        name: Alex Leko
        bio: Desenvolvedor Web, Apaixonado por tecnologia. Trabalhando com as linguagens C#, NodeJS, Python, GoLang e frameworks Angular, VueJS e Reactjs.
        external-image: false
        picture: public/images/profile.jpg
        twitter: LekoDeveloper

paginate: 5
paginate_path: '/blog/page:num/'

# post description
share_description: Um blog com o melhor do desenvolvimento web, mobile, e gerenciamento de mídias sociais.

# if it's an external image, update below for true
# better with square images
external-image: false
company_logo: public/images/favicon/icon.png
picture: public/images/profile.jpg

# If you want to include your resume, set to true
# and specify source (external or local).
resume_url: https://www.linkedin.com/in/lekodeveloperweb/

url: https://ldwsolucoesinteligentes.com.br

permalink: /blog/:title/

# To enable google analytics, supply your token below
analytics_google: 'UA-135069212-1'

# if you don't want comments in your posts, leave categories empty
disqus:
    shortname: LDWSolucoesInteligentes # enter this from your disqus account
    categories: [blog, project] # only show disqus for posts that have these categories

# if you don't have any of social below, comment the line
twitter: LekoDeveloper
twitter_icon: public/images/icons/twitter.png
facebook: ldwsolucoesinteligentes
facebook_icon: public/images/icons/facebook.png
instagram: ldwsolucoesinteligentes
linkedin: lekodeveloperweb
linkedin_icon: public/images/icons/linkedin.png
spotify: lekodeveloperweb
github: ldwsolucoesinteligentes
gitlab: lekodeveloperweb
reddit: lekodeveloperweb
medium: lekodeveloperweb
email: lekodeveloperweb@hotmail.com


# Custom vars
version: 2.0.0

github:
  repo: https://github.com/ldwsolucoesinteligentes

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
